["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
contract = [
    "./contracts/contract.cairo",
]
Zapper = [
    "./contracts/Zapper.cairo",
]
ZapperOut = [
    "./contracts/ZapperOut.cairo",
]

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]